/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_2020();
void sub_2030();
void sub_2040();
void sub_2050();
void sub_2060();
void sub_2070();
void sub_2080();
void sub_2090();
void sub_20A0();
void sub_20B0();
void sub_20C0();
void sub_20D0();
void sub_20E0();
void sub_20F0();
void sub_2100();
void sub_2110();
void sub_2120();
void sub_2130();
void sub_2140();
void sub_2150();
void sub_2160();
void sub_2170();
void sub_2180();
void sub_2190();
void sub_21A0();
void sub_21B0();
void sub_21C0();
void sub_21D0();
void sub_21E0();
void sub_21F0();
void sub_2200();
void sub_2210();
void sub_2220();
void sub_2230();
void sub_2240();
void sub_2250();
void sub_2260();
void sub_2270();
void sub_2280();
void sub_2290();
void sub_22A0();
void sub_22B0();
// int _cxa_finalize(void *);
// void *memset(void *s, int c, size_t n);
// int puts(const char *s);
// void __noreturn exit(int status);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// ssize_t read(int fd, void *buf, size_t nbytes);
// void *malloc(size_t size);
// FILE *fopen(const char *filename, const char *modes);
// char *fgets(char *s, int n, FILE *stream);
// __int64 __fastcall OSSL_PROVIDER_load(_QWORD, _QWORD); weak
// __int64 EVP_MD_CTX_new(void); weak
// size_t strlen(const char *s);
// __int64 __fastcall getentropy(_QWORD, _QWORD); weak
// unsigned int sleep(unsigned int seconds);
// __int64 __fastcall EVP_CIPHER_CTX_set_padding(_QWORD, _QWORD); weak
// __int64 __fastcall EVP_DecryptUpdate(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall EVP_EncryptFinal_ex(_QWORD, _QWORD, _QWORD); weak
// char *strcat(char *dest, const char *src);
// __int64 __fastcall EVP_DigestUpdate(_QWORD, _QWORD, _QWORD); weak
// __int64 EVP_md5(void); weak
// __int64 __fastcall EVP_MD_CTX_free(_QWORD); weak
// __int64 __fastcall EVP_CIPHER_CTX_free(_QWORD); weak
// char *strcpy(char *dest, const char *src);
// __int64 __fastcall EVP_DecryptInit_ex(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// void srand(unsigned int seed);
// __int64 __fastcall EVP_DigestInit_ex(_QWORD, _QWORD, _QWORD); weak
// int memcmp(const void *s1, const void *s2, size_t n);
// __int64 EVP_CIPHER_CTX_new(void); weak
// int fclose(FILE *stream);
// __int64 __fastcall OSSL_PROVIDER_unload(_QWORD); weak
// size_t strcspn(const char *s, const char *reject);
// __int64 __fastcall EVP_EncryptInit_ex(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// __int64 EVP_des_ecb(void); weak
// int rand(void);
// ssize_t write(int fd, const void *buf, size_t n);
// __int64 __fastcall EVP_DecryptFinal_ex(_QWORD, _QWORD, _QWORD); weak
// void *memcpy(void *dest, const void *src, size_t n);
// __int64 __fastcall EVP_EncryptUpdate(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall EVP_DigestFinal_ex(_QWORD, _QWORD, _QWORD); weak
// time_t time(time_t *timer);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
void *sub_2590();
__int64 sub_25C0(void); // weak
void *sub_2600();
__int64 sub_2640();
__int64 __fastcall sub_2649(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall sub_27F6(__int64 a1, __int64 a2, unsigned int a3);
__int64 __fastcall sub_2A32(__int64 a1, __int64 a2, unsigned int a3);
unsigned __int64 __fastcall sub_2C56(__int64 a1, __int64 a2);
unsigned __int64 __fastcall sub_2DAA(__int64 a1, __int64 a2);
_BOOL8 __fastcall sub_2EFE(_BYTE *a1, __int64 a2);
ssize_t __fastcall sub_314C(__int64 a1, __int64 a2);
void *__fastcall sub_3299(void *a1, void *a2);
__int64 sub_32DC();
__int64 __fastcall sub_3443(_BYTE *a1, __int64 a2);
int sub_35B3();
int __fastcall sub_3621(void *a1, __int64 a2);
__int64 __fastcall sub_36CD(_BYTE *a1, _BYTE *a2);
unsigned __int64 __fastcall sub_37E3(void *a1, __int64 a2);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN main;
const char byte_4648 = '\xF0'; // idb
const char byte_4659 = '\xF0'; // idb
void *off_6008 = &off_6008; // idb
_UNKNOWN unk_6010; // weak
FILE *stdin; // idb
FILE *stderr; // idb
FILE *stdout; // idb
char byte_6050; // weak
__int64 qword_6060; // weak
__int16 word_6068; // weak
char src[32]; // idb
char byte_6090[32]; // idb
_BYTE byte_60B0[8]; // weak


//----- (0000000000002000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 6210: using guessed type __int64 _gmon_start__(void);

//----- (0000000000002020) ----------------------------------------------------
void sub_2020()
{
  JUMPOUT(0);
}
// 2026: control flows out of bounds to 0

//----- (0000000000002030) ----------------------------------------------------
void sub_2030()
{
  sub_2020();
}

//----- (0000000000002040) ----------------------------------------------------
void sub_2040()
{
  sub_2020();
}

//----- (0000000000002050) ----------------------------------------------------
void sub_2050()
{
  sub_2020();
}

//----- (0000000000002060) ----------------------------------------------------
void sub_2060()
{
  sub_2020();
}

//----- (0000000000002070) ----------------------------------------------------
void sub_2070()
{
  sub_2020();
}

//----- (0000000000002080) ----------------------------------------------------
void sub_2080()
{
  sub_2020();
}

//----- (0000000000002090) ----------------------------------------------------
void sub_2090()
{
  sub_2020();
}

//----- (00000000000020A0) ----------------------------------------------------
void sub_20A0()
{
  sub_2020();
}

//----- (00000000000020B0) ----------------------------------------------------
void sub_20B0()
{
  sub_2020();
}

//----- (00000000000020C0) ----------------------------------------------------
void sub_20C0()
{
  sub_2020();
}

//----- (00000000000020D0) ----------------------------------------------------
void sub_20D0()
{
  sub_2020();
}

//----- (00000000000020E0) ----------------------------------------------------
void sub_20E0()
{
  sub_2020();
}

//----- (00000000000020F0) ----------------------------------------------------
void sub_20F0()
{
  sub_2020();
}

//----- (0000000000002100) ----------------------------------------------------
void sub_2100()
{
  sub_2020();
}

//----- (0000000000002110) ----------------------------------------------------
void sub_2110()
{
  sub_2020();
}

//----- (0000000000002120) ----------------------------------------------------
void sub_2120()
{
  sub_2020();
}

//----- (0000000000002130) ----------------------------------------------------
void sub_2130()
{
  sub_2020();
}

//----- (0000000000002140) ----------------------------------------------------
void sub_2140()
{
  sub_2020();
}

//----- (0000000000002150) ----------------------------------------------------
void sub_2150()
{
  sub_2020();
}

//----- (0000000000002160) ----------------------------------------------------
void sub_2160()
{
  sub_2020();
}

//----- (0000000000002170) ----------------------------------------------------
void sub_2170()
{
  sub_2020();
}

//----- (0000000000002180) ----------------------------------------------------
void sub_2180()
{
  sub_2020();
}

//----- (0000000000002190) ----------------------------------------------------
void sub_2190()
{
  sub_2020();
}

//----- (00000000000021A0) ----------------------------------------------------
void sub_21A0()
{
  sub_2020();
}

//----- (00000000000021B0) ----------------------------------------------------
void sub_21B0()
{
  sub_2020();
}

//----- (00000000000021C0) ----------------------------------------------------
void sub_21C0()
{
  sub_2020();
}

//----- (00000000000021D0) ----------------------------------------------------
void sub_21D0()
{
  sub_2020();
}

//----- (00000000000021E0) ----------------------------------------------------
void sub_21E0()
{
  sub_2020();
}

//----- (00000000000021F0) ----------------------------------------------------
void sub_21F0()
{
  sub_2020();
}

//----- (0000000000002200) ----------------------------------------------------
void sub_2200()
{
  sub_2020();
}

//----- (0000000000002210) ----------------------------------------------------
void sub_2210()
{
  sub_2020();
}

//----- (0000000000002220) ----------------------------------------------------
void sub_2220()
{
  sub_2020();
}

//----- (0000000000002230) ----------------------------------------------------
void sub_2230()
{
  sub_2020();
}

//----- (0000000000002240) ----------------------------------------------------
void sub_2240()
{
  sub_2020();
}

//----- (0000000000002250) ----------------------------------------------------
void sub_2250()
{
  sub_2020();
}

//----- (0000000000002260) ----------------------------------------------------
void sub_2260()
{
  sub_2020();
}

//----- (0000000000002270) ----------------------------------------------------
void sub_2270()
{
  sub_2020();
}

//----- (0000000000002280) ----------------------------------------------------
void sub_2280()
{
  sub_2020();
}

//----- (0000000000002290) ----------------------------------------------------
void sub_2290()
{
  sub_2020();
}

//----- (00000000000022A0) ----------------------------------------------------
void sub_22A0()
{
  sub_2020();
}

//----- (00000000000022B0) ----------------------------------------------------
void sub_22B0()
{
  sub_2020();
}

//----- (0000000000002560) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 256A: positive sp value 8 has been found
// 2571: variable 'v3' is possibly undefined

//----- (0000000000002590) ----------------------------------------------------
void *sub_2590()
{
  return &unk_6010;
}

//----- (00000000000025C0) ----------------------------------------------------
__int64 sub_25C0()
{
  return 0;
}
// 25C0: using guessed type __int64 sub_25C0();

//----- (0000000000002600) ----------------------------------------------------
void *sub_2600()
{
  void *result; // rax

  if ( !byte_6050 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_6008);
    result = sub_2590();
    byte_6050 = 1;
  }
  return result;
}
// 6050: using guessed type char byte_6050;

//----- (0000000000002640) ----------------------------------------------------
// attributes: thunk
__int64 sub_2640()
{
  return sub_25C0();
}
// 25C0: using guessed type __int64 sub_25C0(void);

//----- (0000000000002649) ----------------------------------------------------
__int64 __fastcall sub_2649(__int64 a1, __int64 a2, __int64 a3)
{
  _BYTE v5[4]; // [rsp+2Ch] [rbp-14h] BYREF
  __int64 v6; // [rsp+30h] [rbp-10h]
  __int64 v7; // [rsp+38h] [rbp-8h]

  v6 = EVP_MD_CTX_new();
  if ( !v6 )
  {
    fwrite("Error: EVP_MD_CTX_new failed\n", 1u, 0x1Du, stderr);
    exit(1);
  }
  v7 = EVP_md5();
  if ( !v7 )
  {
    fwrite("Error: EVP_md5 failed\n", 1u, 0x16u, stderr);
    EVP_MD_CTX_free(v6);
    exit(1);
  }
  if ( (unsigned int)EVP_DigestInit_ex(v6, v7, 0) != 1 )
  {
    fwrite("Error: EVP_DigestInit_ex failed\n", 1u, 0x20u, stderr);
    EVP_MD_CTX_free(v6);
    exit(1);
  }
  if ( (unsigned int)EVP_DigestUpdate(v6, a1, a2) != 1 )
  {
    fwrite("Error: EVP_DigestUpdate failed\n", 1u, 0x1Fu, stderr);
    EVP_MD_CTX_free(v6);
    exit(1);
  }
  if ( (unsigned int)EVP_DigestFinal_ex(v6, a3, v5) != 1 )
  {
    fwrite("Error: EVP_DigestFinal_ex failed\n", 1u, 0x21u, stderr);
    EVP_MD_CTX_free(v6);
    exit(1);
  }
  return EVP_MD_CTX_free(v6);
}
// 2360: using guessed type __int64 EVP_MD_CTX_new(void);
// 23E0: using guessed type __int64 __fastcall EVP_DigestUpdate(_QWORD, _QWORD, _QWORD);
// 23F0: using guessed type __int64 EVP_md5(void);
// 2400: using guessed type __int64 __fastcall EVP_MD_CTX_free(_QWORD);
// 2460: using guessed type __int64 __fastcall EVP_DigestInit_ex(_QWORD, _QWORD, _QWORD);
// 2540: using guessed type __int64 __fastcall EVP_DigestFinal_ex(_QWORD, _QWORD, _QWORD);

//----- (00000000000027F6) ----------------------------------------------------
__int64 __fastcall sub_27F6(__int64 a1, __int64 a2, unsigned int a3)
{
  __int64 v3; // rax
  int v6; // [rsp+28h] [rbp-18h] BYREF
  int v7; // [rsp+2Ch] [rbp-14h]
  __int64 v8; // [rsp+30h] [rbp-10h]
  __int64 v9; // [rsp+38h] [rbp-8h]

  v8 = OSSL_PROVIDER_load(0, "legacy");
  if ( !v8 )
  {
    fwrite("Error: OSSL_PROVIDER_load failed\n", 1u, 0x21u, stderr);
    exit(1);
  }
  v9 = EVP_CIPHER_CTX_new();
  if ( !v9 )
  {
    fwrite("Error: EVP_CIPHER_CTX_new failed\n", 1u, 0x21u, stderr);
    OSSL_PROVIDER_unload(v8);
    exit(1);
  }
  v3 = EVP_des_ecb();
  if ( (unsigned int)EVP_EncryptInit_ex(v9, v3, 0, &qword_6060, 0) != 1 )
  {
    fwrite("Error: EVP_EncryptInit_ex failed\n", 1u, 0x21u, stderr);
    EVP_CIPHER_CTX_free(v9);
    OSSL_PROVIDER_unload(v8);
    exit(1);
  }
  EVP_CIPHER_CTX_set_padding(v9, 0);
  v6 = 0;
  v7 = 0;
  if ( (unsigned int)EVP_EncryptUpdate(v9, a2, &v6, a1, a3) != 1 )
  {
    fwrite("Error: EVP_EncryptUpdate failed\n", 1u, 0x20u, stderr);
    EVP_CIPHER_CTX_free(v9);
    OSSL_PROVIDER_unload(v8);
    exit(1);
  }
  v7 += v6;
  if ( (unsigned int)EVP_EncryptFinal_ex(v9, v7 + a2, &v6) != 1 )
  {
    fwrite("Error: EVP_EncryptFinal_ex failed\n", 1u, 0x22u, stderr);
    EVP_CIPHER_CTX_free(v9);
    OSSL_PROVIDER_unload(v8);
    exit(1);
  }
  v7 += v6;
  EVP_CIPHER_CTX_free(v9);
  return OSSL_PROVIDER_unload(v8);
}
// 2350: using guessed type __int64 __fastcall OSSL_PROVIDER_load(_QWORD, _QWORD);
// 23A0: using guessed type __int64 __fastcall EVP_CIPHER_CTX_set_padding(_QWORD, _QWORD);
// 23C0: using guessed type __int64 __fastcall EVP_EncryptFinal_ex(_QWORD, _QWORD, _QWORD);
// 2410: using guessed type __int64 __fastcall EVP_CIPHER_CTX_free(_QWORD);
// 2480: using guessed type __int64 EVP_CIPHER_CTX_new(void);
// 24A0: using guessed type __int64 __fastcall OSSL_PROVIDER_unload(_QWORD);
// 24C0: using guessed type __int64 __fastcall EVP_EncryptInit_ex(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 24E0: using guessed type __int64 EVP_des_ecb(void);
// 2530: using guessed type __int64 __fastcall EVP_EncryptUpdate(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 6060: using guessed type __int64 qword_6060;

//----- (0000000000002A32) ----------------------------------------------------
__int64 __fastcall sub_2A32(__int64 a1, __int64 a2, unsigned int a3)
{
  __int64 v3; // rax
  int v6; // [rsp+28h] [rbp-18h] BYREF
  int v7; // [rsp+2Ch] [rbp-14h]
  __int64 v8; // [rsp+30h] [rbp-10h]
  __int64 v9; // [rsp+38h] [rbp-8h]

  v8 = OSSL_PROVIDER_load(0, "legacy");
  if ( !v8 )
  {
    fwrite("Error: OSSL_PROVIDER_load failed\n", 1u, 0x21u, stderr);
    exit(1);
  }
  v9 = EVP_CIPHER_CTX_new();
  if ( !v9 )
  {
    fwrite("Error: EVP_CIPHER_CTX_new failed\n", 1u, 0x21u, stderr);
    OSSL_PROVIDER_unload(v8);
    exit(1);
  }
  v3 = EVP_des_ecb();
  if ( (unsigned int)EVP_DecryptInit_ex(v9, v3, 0, &qword_6060, 0) != 1 )
  {
    fwrite("Error: EVP_DecryptInit_ex failed\n", 1u, 0x21u, stderr);
    EVP_CIPHER_CTX_free(v9);
    OSSL_PROVIDER_unload(v8);
    exit(1);
  }
  EVP_CIPHER_CTX_set_padding(v9, 0);
  v6 = 0;
  v7 = 0;
  if ( (unsigned int)EVP_DecryptUpdate(v9, a2, &v6, a1, a3) != 1 )
  {
    fwrite("Error: EVP_DecryptUpdate failed\n", 1u, 0x20u, stderr);
    EVP_CIPHER_CTX_free(v9);
    exit(1);
  }
  v7 += v6;
  if ( (unsigned int)EVP_DecryptFinal_ex(v9, v7 + a2, &v6) != 1 )
  {
    fwrite("Error: EVP_DecryptFinal_ex failed\n", 1u, 0x22u, stderr);
    EVP_CIPHER_CTX_free(v9);
    exit(1);
  }
  v7 += v6;
  EVP_CIPHER_CTX_free(v9);
  return OSSL_PROVIDER_unload(v8);
}
// 2350: using guessed type __int64 __fastcall OSSL_PROVIDER_load(_QWORD, _QWORD);
// 23A0: using guessed type __int64 __fastcall EVP_CIPHER_CTX_set_padding(_QWORD, _QWORD);
// 23B0: using guessed type __int64 __fastcall EVP_DecryptUpdate(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 2410: using guessed type __int64 __fastcall EVP_CIPHER_CTX_free(_QWORD);
// 2440: using guessed type __int64 __fastcall EVP_DecryptInit_ex(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 2480: using guessed type __int64 EVP_CIPHER_CTX_new(void);
// 24A0: using guessed type __int64 __fastcall OSSL_PROVIDER_unload(_QWORD);
// 24E0: using guessed type __int64 EVP_des_ecb(void);
// 2510: using guessed type __int64 __fastcall EVP_DecryptFinal_ex(_QWORD, _QWORD, _QWORD);
// 6060: using guessed type __int64 qword_6060;

//----- (0000000000002C56) ----------------------------------------------------
unsigned __int64 __fastcall sub_2C56(__int64 a1, __int64 a2)
{
  unsigned __int16 v2; // ax
  unsigned __int64 v3; // rax
  void *v4; // rsp
  __int64 v5; // rcx
  __int64 v6; // rdx
  __int64 v8; // [rsp+8h] [rbp-50h] BYREF
  __int64 v9; // [rsp+10h] [rbp-48h]
  __int64 v10; // [rsp+18h] [rbp-40h]
  void *src; // [rsp+20h] [rbp-38h]
  _QWORD v12[3]; // [rsp+28h] [rbp-30h] BYREF
  unsigned __int64 v13; // [rsp+40h] [rbp-18h]

  v9 = a1;
  v8 = a2;
  v13 = __readfsqword(0x28u);
  v2 = *(_WORD *)(a2 + 5);
  v10 = v2 - 1LL;
  v3 = 16 * (((unsigned __int64)v2 + 15) / 0x10);
  while ( &v8 != (__int64 *)((char *)&v8 - (v3 & 0xFFFFFFFFFFFFF000LL)) )
    ;
  v4 = alloca(v3 & 0xFFF);
  if ( (v3 & 0xFFF) != 0 )
    *(__int64 *)((char *)&v8 + (v3 & 0xFFF) - 8) = *(__int64 *)((char *)&v8 + (v3 & 0xFFF) - 8);
  src = &v8;
  sub_2A32(v8 + 24, (__int64)&v8, *(unsigned __int16 *)(v8 + 5));
  memcpy((void *)(v9 + 24), src, *(unsigned __int16 *)(v8 + 5));
  sub_2649(v9, *(unsigned __int16 *)(v8 + 5) + 24LL, (__int64)v12);
  v5 = v9 + 8;
  v6 = v12[1];
  *(_QWORD *)(v9 + 8) = v12[0];
  *(_QWORD *)(v5 + 8) = v6;
  return v13 - __readfsqword(0x28u);
}

//----- (0000000000002DAA) ----------------------------------------------------
unsigned __int64 __fastcall sub_2DAA(__int64 a1, __int64 a2)
{
  __int64 v2; // rdx
  unsigned __int16 v3; // ax
  unsigned __int64 v4; // rax
  void *v5; // rsp
  _QWORD v7[3]; // [rsp+8h] [rbp-50h] BYREF
  void *src; // [rsp+20h] [rbp-38h]
  _QWORD v9[3]; // [rsp+28h] [rbp-30h] BYREF
  unsigned __int64 v10; // [rsp+40h] [rbp-18h]

  v7[1] = a1;
  v7[0] = a2;
  v10 = __readfsqword(0x28u);
  sub_2649(a1, *(unsigned __int16 *)(a2 + 5) + 24LL, (__int64)v9);
  v2 = v9[1];
  *(_QWORD *)(a2 + 8) = v9[0];
  *(_QWORD *)(a2 + 16) = v2;
  v3 = *(_WORD *)(v7[0] + 5LL);
  v7[2] = v3 - 1LL;
  v4 = 16 * (((unsigned __int64)v3 + 15) / 0x10);
  while ( v7 != (_QWORD *)((char *)v7 - (v4 & 0xFFFFFFFFFFFFF000LL)) )
    ;
  v5 = alloca(v4 & 0xFFF);
  if ( (v4 & 0xFFF) != 0 )
    *(_QWORD *)((char *)&v7[-1] + (v4 & 0xFFF)) = *(_QWORD *)((char *)&v7[-1] + (v4 & 0xFFF));
  src = v7;
  sub_27F6(v7[0] + 24LL, (__int64)v7, *(unsigned __int16 *)(v7[0] + 5LL));
  memcpy((void *)(v7[0] + 24LL), src, *(unsigned __int16 *)(v7[0] + 5LL));
  return v10 - __readfsqword(0x28u);
}

//----- (0000000000002EFE) ----------------------------------------------------
_BOOL8 __fastcall sub_2EFE(_BYTE *a1, __int64 a2)
{
  _BOOL8 result; // rax
  int v3; // ebx
  int v4; // eax
  __int64 v5; // rdx
  unsigned __int64 v6; // [rsp+18h] [rbp-18h]

  v6 = read(0, a1, 0x68u);
  if ( v6 <= 0x17 )
    return 0;
  *(_BYTE *)a2 = *a1;
  *(_BYTE *)(a2 + 1) = a1[1];
  *(_BYTE *)(a2 + 2) = a1[2];
  if ( *(_BYTE *)(a2 + 2) != 1 )
    return 0;
  *(_WORD *)(a2 + 3) = _byteswap_ushort(*(_WORD *)(a1 + 3));
  if ( *(_WORD *)(a2 + 3) != word_6068 )
    return 0;
  ++word_6068;
  *(_WORD *)(a2 + 5) = _byteswap_ushort(*(_WORD *)(a1 + 5));
  if ( (*(_WORD *)(a2 + 5) & 7) != 0 || v6 != *(unsigned __int16 *)(a2 + 5) + 24LL )
    return 0;
  *(_BYTE *)(a2 + 7) = a1[7];
  v3 = *(unsigned __int8 *)(a2 + 7);
  v4 = rand();
  if ( v3 != (unsigned __int8)(((unsigned int)(v4 >> 31) >> 24) + v4) - ((unsigned int)(v4 >> 31) >> 24) )
    return 0;
  v5 = *((_QWORD *)a1 + 2);
  *(_QWORD *)(a2 + 8) = *((_QWORD *)a1 + 1);
  *(_QWORD *)(a2 + 16) = v5;
  memset(a1 + 8, 0, 0x10u);
  memcpy((void *)(a2 + 24), a1 + 24, *(unsigned __int16 *)(a2 + 5));
  memset(a1 + 24, 0, *(unsigned __int16 *)(a2 + 5));
  result = 1;
  if ( *(_BYTE *)a2 == 2 )
  {
    sub_2C56((__int64)a1, a2);
    if ( memcmp((const void *)(a2 + 8), a1 + 8, 0x10u) )
      return 0;
  }
  return result;
}
// 6068: using guessed type __int16 word_6068;

//----- (000000000000314C) ----------------------------------------------------
ssize_t __fastcall sub_314C(__int64 a1, __int64 a2)
{
  __int16 v2; // ax
  __int64 v3; // rdx

  *(_BYTE *)a2 = 2;
  *(_BYTE *)(a2 + 2) = 0;
  v2 = word_6068++;
  *(_WORD *)(a2 + 3) = v2;
  *(_BYTE *)(a2 + 7) = rand();
  memcpy((void *)a1, (const void *)a2, *(unsigned __int16 *)(a2 + 5) + 24LL);
  *(_BYTE *)(a1 + 3) = HIBYTE(*(_WORD *)(a2 + 3));
  *(_BYTE *)(a1 + 4) = *(_WORD *)(a2 + 3);
  *(_BYTE *)(a1 + 5) = HIBYTE(*(_WORD *)(a2 + 5));
  *(_BYTE *)(a1 + 6) = *(_WORD *)(a2 + 5);
  sub_2DAA(a1, a2);
  v3 = *(_QWORD *)(a2 + 16);
  *(_QWORD *)(a1 + 8) = *(_QWORD *)(a2 + 8);
  *(_QWORD *)(a1 + 16) = v3;
  memcpy((void *)(a1 + 24), (const void *)(a2 + 24), *(unsigned __int16 *)(a2 + 5));
  return write(1, (const void *)a1, *(unsigned __int16 *)(a2 + 5) + 24LL);
}
// 6068: using guessed type __int16 word_6068;

//----- (0000000000003299) ----------------------------------------------------
void *__fastcall sub_3299(void *a1, void *a2)
{
  memset(a1, 0, 0x68u);
  return memset(a2, 0, 0x68u);
}

//----- (00000000000032DC) ----------------------------------------------------
__int64 sub_32DC()
{
  puts("Enrolling your spaceship...");
  puts("Please enter your spaceship name: ");
  if ( !fgets(src, 25, stdin) )
  {
    fwrite("Error: fgets failed\n", 1u, 0x14u, stderr);
    exit(1);
  }
  src[strcspn(src, "\n")] = 0;
  if ( src[0] )
  {
    puts("Please enter your access code: ");
    if ( fgets(byte_6090, 25, stdin) && (byte_6090[strcspn(byte_6090, "\n")] = 0, byte_6090[0]) )
    {
      puts("Your spaceship is successfully enrolled!");
      return 1;
    }
    else
    {
      puts("Your access code is invalid.");
      return 0;
    }
  }
  else
  {
    puts("Your spaceship name is invalid.");
    return 0;
  }
}

//----- (0000000000003443) ----------------------------------------------------
__int64 __fastcall sub_3443(_BYTE *a1, __int64 a2)
{
  size_t v3; // rax
  __int64 v4; // [rsp+10h] [rbp-50h] BYREF
  char dest[56]; // [rsp+20h] [rbp-40h] BYREF
  unsigned __int64 v6; // [rsp+58h] [rbp-8h]

  v6 = __readfsqword(0x28u);
  puts("Authenticating your entry...");
  if ( sub_2EFE(a1, a2) && *(_BYTE *)a2 == 1 && *(_BYTE *)(a2 + 1) == 5 )
  {
    strcpy(dest, src);
    strcat(dest, byte_6090);
    if ( strlen(dest) == *(unsigned __int16 *)(a2 + 5)
      || !memcmp((const void *)(a2 + 24), dest, *(unsigned __int16 *)(a2 + 5)) )
    {
      v3 = strlen(dest);
      sub_2649((__int64)dest, v3, (__int64)&v4);
      qword_6060 = v4;
      puts("You are successfully authenticated!");
      return 1;
    }
    else
    {
      puts("You are not authorized to enter the portal.");
      return 0;
    }
  }
  else
  {
    puts("You are not authorized to enter the portal.");
    return 0;
  }
}
// 6060: using guessed type __int64 qword_6060;

//----- (00000000000035B3) ----------------------------------------------------
int sub_35B3()
{
  puts("Activating wormhole...");
  if ( (unsigned int)getentropy(&unk_60B0, 8) )
  {
    fwrite("Error: getentropy failed\n", 1u, 0x19u, stderr);
    exit(1);
  }
  return puts("Wormhole activated!");
}
// 2380: using guessed type __int64 __fastcall getentropy(_QWORD, _QWORD);

//----- (0000000000003621) ----------------------------------------------------
int __fastcall sub_3621(void *a1, __int64 a2)
{
  unsigned __int64 i; // [rsp+18h] [rbp-8h]

  puts("Leaking signature...");
  sub_3299(a1, (void *)a2);
  *(_BYTE *)(a2 + 1) = 13;
  *(_WORD *)(a2 + 5) = 8;
  for ( i = 0; i <= 7; ++i )
    *(_BYTE *)(a2 + i + 24) = ~byte_60B0[7 - i];
  sub_314C((__int64)a1, a2);
  return puts("Signature leaked!");
}
// 60B0: using guessed type _BYTE byte_60B0[8];

//----- (00000000000036CD) ----------------------------------------------------
__int64 __fastcall sub_36CD(_BYTE *a1, _BYTE *a2)
{
  unsigned __int64 i; // [rsp+18h] [rbp-18h]
  _QWORD s1[2]; // [rsp+20h] [rbp-10h] BYREF

  s1[1] = __readfsqword(0x28u);
  puts("Validating signature...");
  sub_3299(a1, a2);
  if ( !sub_2EFE(a1, (__int64)a2) )
    goto LABEL_8;
  if ( a2[1] != 76 )
    goto LABEL_8;
  for ( i = 0; i <= 7; ++i )
    *((_BYTE *)s1 + i) = a2[7] ^ a1[i + 24];
  if ( !memcmp(s1, byte_60B0, 8u) )
  {
    qword_6060 = s1[0];
    puts("Your wormhole signature is valid!");
    return 1;
  }
  else
  {
LABEL_8:
    puts("Your wormhole signature is invalid.");
    return 0;
  }
}
// 6060: using guessed type __int64 qword_6060;
// 60B0: using guessed type _BYTE byte_60B0[8];

//----- (00000000000037E3) ----------------------------------------------------
unsigned __int64 __fastcall sub_37E3(void *a1, __int64 a2)
{
  __int16 v2; // bx
  FILE *stream; // [rsp+18h] [rbp-128h]
  char s[264]; // [rsp+20h] [rbp-120h] BYREF
  unsigned __int64 v6; // [rsp+128h] [rbp-18h]

  v6 = __readfsqword(0x28u);
  puts("Sending coordinate...");
  sub_3299(a1, (void *)a2);
  memset(s, 0, 0x100u);
  stream = fopen("flag.txt", "r");
  if ( !stream )
  {
    fwrite("Error: fopen failed\n", 1u, 0x14u, stderr);
    exit(1);
  }
  if ( !fgets(s, 256, stream) )
  {
    fwrite("Error: fgets failed\n", 1u, 0x14u, stderr);
    fclose(stream);
    exit(1);
  }
  fclose(stream);
  *(_BYTE *)(a2 + 1) = 66;
  v2 = strlen(s);
  *(_WORD *)(a2 + 5) = v2 + (-(__int16)strlen(s) & 7);
  memcpy((void *)(a2 + 24), s, *(unsigned __int16 *)(a2 + 5));
  sub_314C((__int64)a1, a2);
  puts("Coordinate sent!");
  return v6 - __readfsqword(0x28u);
}

//----- (00000000000039BF) ----------------------------------------------------
__int64 __fastcall main(int a1, char **a2, char **a3)
{
  unsigned int v3; // eax
  void *v5; // [rsp+0h] [rbp-10h]
  void *v6; // [rsp+8h] [rbp-8h]

  setvbuf(stdin, 0, 2, 0);
  setvbuf(stdout, 0, 2, 0);
  setvbuf(stderr, 0, 2, 0);
  v3 = time(0);
  srand(v3);
  puts("Welcome to the intelligent portal in space!");
  while ( !(unsigned int)sub_32DC() )
    ;
  puts("It will send you home without telling it the destination!");
  puts("You have to communicate with it in a special way!");
  v5 = malloc(0x68u);
  v6 = malloc(0x68u);
  while ( !(unsigned int)sub_3443(v5, v6) )
    ;
  puts("Your spacehsip is now being teleported to the destination!");
  sleep(1u);
  puts("Oops!!!");
  puts("The intelligent portal has been invaded by the aliens!");
  puts("You are trapped!");
  sub_35B3();
  puts("The intelligent portal tried its best to open a wormhole for you before it lost its consciousness!");
  puts("But you have to escape by yourself with the leaked information!");
  sub_3621(v5, v6);
  do
    puts(&byte_4648);
  while ( !(unsigned int)sub_36CD(v5, v6) );
  puts(&byte_4659);
  puts("Goodbye, alien!");
  puts("Escape is not the end!");
  puts("You are abandoned in unknown realms in the universe with the coordinate!");
  sub_37E3(v5, v6);
  return 0;
}
// 32DC: using guessed type __int64 sub_32DC(void);
// 3443: using guessed type __int64 __fastcall sub_3443(_QWORD, _QWORD);
// 35B3: using guessed type __int64 sub_35B3(void);
// 3621: using guessed type __int64 __fastcall sub_3621(_QWORD, _QWORD);
// 36CD: using guessed type __int64 __fastcall sub_36CD(_QWORD, _QWORD);
// 37E3: using guessed type __int64 __fastcall sub_37E3(_QWORD, _QWORD);

//----- (0000000000003BB0) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=150 queued=64 decompiled=64 lumina nreq=0 worse=0 better=0
// ALL OK, 64 function(s) have been successfully decompiled
