#!/usr/bin/env python3
import requests
import argparse
import os, sys
import gzip
import shutil

def get_tokens():
    """Gets a csrf token"""
    url = "https://dogbolt.org"
    res = requests.get(url)

    return res.cookies.get("csrftoken")

def send_binary(file_path):
    """Uploads the binary to dogbolt and returns the id"""
    url = 'https://dogbolt.org/api/binaries/'

    with open(file_path, 'rb') as f:
        file_content = f.read()

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0',
        'Accept': '*/*',
        'Accept-Language': 'en-US,en;q=0.5',
        'Accept-Encoding': 'gzip, deflate, br, zstd',
        'Referer': 'https://dogbolt.org/',
        'Origin': 'https://dogbolt.org',
        'Connection': 'keep-alive',
        'Cookie': csrf_token,
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'same-origin',
        'Sec-Fetch-Site': 'same-origin',
        'Priority': 'u=4',
        'TE': 'trailers'
    }

    files = {
        'file': (os.path.basename(file_path), file_content, 'application/octet-stream'),
    }

    # send binary and return the id
    response = requests.post(url, headers=headers, files=files)
    id = response.json()["id"]

    return id

def get_decompiled_url(id, decompiler):
    """Gets the url for the decompilation given an id and decompiler"""
    args_mapping = {
        "hexrays": "Hex-Rays",
        "ghidra": "Ghidra",
        "angr": "angr",
        "binja": "BinaryNinja"
    }

    assert decompiler in args_mapping.keys(), "Invalid decompiler"  # not possible
    decompiler = args_mapping[decompiler]

    url = f"https://dogbolt.org/api/binaries/{id}/decompilations"

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0',
        'Accept': '*/*',
        'Accept-Language': 'en-US,en;q=0.5',
        'Accept-Encoding': 'gzip, deflate, br, zstd',
        'Referer': f"https://dogbolt.org/?id={id}",
        'Connection': 'keep-alive',
        'Cookie': csrf_token,
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'same-origin',
        'Sec-Fetch-Site': 'same-origin',
        'Priority': 'u=4',
    }

    res = requests.get(url, headers=headers)
    results = res.json()["results"]

    decomp_result = [x for x in results if x["decompiler"]["name"] == decompiler][0]
    decomp_url = decomp_result["download_url"]

    return decomp_url

def download_file(url, output_path) -> None:
    """Downloads the gzipped file and writes it to the output path"""
    with requests.get(url, stream=True) as response:
        response.raise_for_status()  # Check if the download was successful
        with gzip.open(response.raw, 'rb') as f_in:
            with open(output_path, 'wb') as f_out:
                shutil.copyfileobj(f_in, f_out)
    return

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Send a request to Dogbolt API and save the output.')
    parser.add_argument('-o', '--output', type=str, default='decomp.txt',
                        help='Specify the output file (default: decomp.txt)')
    parser.add_argument('-d', '--decompiler', type=str, choices=['angr', 'ghidra', 'hexrays', 'binja'], default='hexrays',
                        help='Specify the decompiler to use (default: hexrays)')
    parser.add_argument('file_path', type=str, help='Path to the file to be sent')
    args = parser.parse_args()

    try:
        csrf_token = get_tokens()
    except ConnectionError:
        print("Error: No internet connection")
        exit(1)

    try:
        id = send_binary(args.file_path)
        decomp_url = get_decompiled_url(id, args.decompiler)
        download_file(decomp_url, args.output)
    except Exception as e:
        print("Error occured, retrying...")
        os.execve(sys.executable, [sys.executable] + sys.argv, os.environ)
